### ISSUE TITLE
Can not turn on "Record computer sounds"

### ISSUE THREAD

**Issue by mikield** [artemanufrij/screencast#10]
Check out the screenshot.
The check box is disabled, and when I am recording - the sound doesn't exist, tested on youtube music.
![2017-08-05 14 20 28](https://user-images.githubusercontent.com/4073672/28995430-440018a2-79e9-11e7-9277-d5cafb799e77.png)

**Comment by artemanufrij** [comment]
@mikield could you test this PR: #12

**Comment by simpler360** [comment]
Even I face the same issue.

**Comment by artemanufrij** [comment]
@simpler360 I fixed it in #12. Could you test it?

**Comment by artemanufrij** [comment]
fixed in #12
