### ISSUE TITLE
Suggestion: Session ending

### ISSUE THREAD

**Issue by WebShapedBiz** [artemanufrij/screencast#13]
Hi.
I would suggest to end a screencast recording session at the click on the icon, before final window. This way we don't have to cut the last few seconds out when doing tutorials or similar.

Cheers.

**Comment by Djaler** [comment]
Hmm, for me it alreay works like you want it

**Comment by WebShapedBiz** [comment]
I'm sorry Artem, I feel stupid, the issue is gone now. Could it be that it was fixed in last few releases? Previously I had this issue where my clicking Finish button was always recorded as well.
Anyhow, thank you for your time and effort.
Cheers.

**Comment by artemanufrij** [comment]
I'm going to close it...
