### ISSUE TITLE
Screencast folder

### ISSUE THREAD

**Issue by Djaler** [artemanufrij/screencast#14]
Screencast always create folder ~/Videos/Screencasts after app launch. I see your commit where you add this functionality. But I don't understand why. After screencast ending I choose a directory to save file. If I need a separate folder for screencasts, I'll create it manually

**Comment by artemanufrij** [comment]
`Screenshot app` saves pictures in `~/Pictures/Screenshots`
`Camera` saves pictures in `~/Pictures/Webcam` and videos in `~/Videos/Webcam`
-> `Screencast` saves screencasts in `~/Videos/Screencasts`

it's just consistently

**Comment by Djaler** [comment]
But this apps doesn't create folders at every launch.

**Comment by artemanufrij** [comment]
I will check it

**Comment by Djaler** [comment]
Also, there you are even not use this folder. You just make it default in saving dialog. But, I think, default folder setting should change if I select another folder.

**Comment by artemanufrij** [comment]
I will save last choosed folder

**Comment by artemanufrij** [comment]
@Djaler could you test current master brunch, please?

**Comment by Djaler** [comment]
It works as expect

**Comment by artemanufrij** [comment]
Thank you! I will release it asap.

**Comment by Djaler** [comment]
Can you make a release with this fix?

**Comment by artemanufrij** [comment]
@Djaler done... is waiting for human testing
