### ISSUE TITLE
Ability to start recording after defined time

### ISSUE THREAD

**Issue by franklevel** [artemanufrij/screencast#24]
Allow to define a time interval to start recording

**Comment by artemanufrij** [comment]
@franklevel I added a "Delay in seconds" property. Could you test curren master branch plases?

**Comment by artemanufrij** [comment]
released with last version:
![screenshot from 2018-03-04 16 35 54](https://user-images.githubusercontent.com/16517095/36947298-2c6735c2-1fca-11e8-962a-dd80f4d374b4.png)

**Comment by franklevel** [comment]
I found this issue. Translation has wrong chars.
![captura realizada el 2018-03-05 10 38 42](https://user-images.githubusercontent.com/1608952/36977944-aa08b14e-2061-11e8-9924-118297f2292a.png)

I fixed and I going to send you a pull request.

**Comment by artemanufrij** [comment]
@franklevel would you open one?

**Comment by franklevel** [comment]
@artemanufrij yes, i'll do it
