### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by ttosttos** [artemanufrij/screencast#25]
I'd be good to have a basic set of keyboard shortcuts (e.g. start/stop, pause).  Couldn't find any documentation or evidence of implementation.  Particularly useful when recording the entire screen.

**Comment by artemanufrij** [comment]
@ttosttos what shortcuts would be useful?

**Comment by ttosttos** [comment]
I'd suggest focusing on the controls for the actual recording: start, pause, continue and finish.  The ultimate goal should be to allow the user to do any recording (full screen or not) without having the app GUI show up on the recording.  My assumption is that keyboard shortcuts are the easiest approach to meet that requirement. For elementaryOS, I'd guess the shortcuts should integrate with "System Settings → Keyboard → Shortcuts → Applications" .

**Comment by artemanufrij** [comment]
@ttosttos I adden a media key listener. so you can now use [Play/Pause] for toggle recording [Stop] to finish it. Could you test current master branch please?

**Comment by artemanufrij** [comment]
Listen for Media Keys was released with last version
