### ISSUE TITLE
Fix wrong chars in spanish translation

### ISSUE THREAD

**Issue by franklevel** [artemanufrij/screencast#26]
Fix spanish PO file translation.
![captura realizada el 2018-03-05 10 38 42](https://user-images.githubusercontent.com/1608952/36979330-e4b99f2a-2065-11e8-8872-212aec9ed345.png)

**Comment by artemanufrij** [comment]
@franklevel would you send me a new PO file? :smile:

**Comment by franklevel** [comment]
Of course, tell me, how I do? Push o what?

**Comment by artemanufrij** [comment]
@franklevel PS: for translating you can use https://poedit.net/

the easiest way for you is just push it into this conversation.

**Comment by franklevel** [comment]
Ok.

msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-03 13:40+0100\n"
"PO-Revision-Date: 2018-03-05 09:49-0300\n"
"Last-Translator: Juan Velandia <juankz.github.io>\n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.7.1\n"

#: /home/artem/Projekte/screencast/po/../src//Widgets/countdown.vala:38
msgid "Recording starts in"
msgstr "La grabación empieza en"

#: /home/artem/Projekte/screencast/po/../src//Widgets/countdown.vala:45
msgid "Focus Screencast to stop recording"
msgstr "Enfoca la aplicación Grabar Pantalla para detener la grabación"

#: /home/artem/Projekte/screencast/po/../src//Widgets/keyview.vala:61
msgid "Left"
msgstr "Izq."

#: /home/artem/Projekte/screencast/po/../src//Widgets/keyview.vala:64
msgid "Middle"
msgstr "Medio"

#: /home/artem/Projekte/screencast/po/../src//Widgets/keyview.vala:67
msgid "Right"
msgstr "Der."

#: /home/artem/Projekte/screencast/po/../src//desktop_launcher.vala:22
msgid "Record screencasts"
msgstr "Graba pantallas"

#: /home/artem/Projekte/screencast/po/../src//desktop_launcher.vala:23
msgid "Screencaster"
msgstr "Grabar Pantalla"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:95
#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:516
msgid "Screencast"
msgstr "Grabar Pantalla"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:117
msgid "Monitor"
msgstr "Monitor"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:140
msgid "Fullscreen"
msgstr "Pantalla completa"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:141
msgid "Custom"
msgstr "Personalizar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:158
msgid "Sound"
msgstr "Sonido"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:161
msgid "Video"
msgstr "Video"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:164
msgid "Keyboard"
msgstr "Teclado"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:167
msgid "Mouse"
msgstr "Ratón"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:171
msgid "Record Computer Sounds:"
msgstr "Grabar sonidos del computador"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:173
msgid "Record from Microphone:"
msgstr "Grabar sonidos desde el micrófono"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:176
msgid "Record from Monitor:"
msgstr "Grabar desde el monitor"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:178
msgid "Recording Area:"
msgstr "Grabar Área"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:180
msgid "Width:"
msgstr "Ancho:"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:182
msgid "Height:"
msgstr "Alto:"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:205
msgid "Pressed keys on screen:"
msgstr "Mostrar las teclas presionadas:"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:208
msgid "Mouse clicks on screen:"
msgstr "Mostrar clics:"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:210
msgid "Circle around the cursor:"
msgstr "Círculo alrededor del cursor:"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:216
msgid "Behavior"
msgstr "Comportamiento"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:217
msgid "Appearance"
msgstr "Apariencia"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:231
msgid "Start Recording"
msgstr "Iniciar grabación"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:236
msgid "Close"
msgstr "Cerrar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:444
#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:533
msgid "Recording paused"
msgstr "Grabación en pausa"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:447
msgid "You can continue or finish the recording now"
msgstr "Puede continuar o finalizar la grabación ahora"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:456
msgid "Continue"
msgstr "Continuar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:457
msgid "Continue recording"
msgstr "Continuar grabando"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:459
msgid "Finish"
msgstr "Finalizar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:460
msgid "Stop the recording and save the file"
msgstr "Detener la grabación y guardar el archivo"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:463
msgid "Cancel"
msgstr "Cancelar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:464
msgid "Cancel the recording without saving the file"
msgstr "Cancelar la grabación sin guardar el archivo"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:535
msgid "Pause recording"
msgstr "Pausar grabación"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:556
msgid "Save"
msgstr "Guardar"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:556
msgid "OK"
msgstr "OK"

#: /home/artem/Projekte/screencast/po/../src//MainWindow.vala:559
#, c-format
msgid "Screencast from %s"
msgstr "Grabacion del %s"

#~ msgid "Screencasts"
#~ msgstr "Grabaciones de Pantalla"

#~ msgid "Default"
#~ msgstr "Predeterminado"

**Comment by artemanufrij** [comment]
@franklevel zip file please :smile:

**Comment by franklevel** [comment]
[es.zip](https://github.com/artemanufrij/screencast/files/1781181/es.zip)

**Comment by artemanufrij** [comment]
Thank you @franklevel ! Master branch was fixed. New release will come next weekend.
