### ISSUE TITLE
Indicator status recording for end or pause

### ISSUE THREAD

**Issue by torikulhabib** [artemanufrij/screencast#32]
i hope there is Indicator status recording for end or pause

**Comment by artemanufrij** [comment]
hey @torikulhabib thank you for your fedback.

do you mean something like this?:
https://plus.google.com/+ArtemAnufrij/posts/dWcQyJYJye7

**Comment by torikulhabib** [comment]
Yes Mr. 
But I don't know.  Indicator not show on Juno beta

**Comment by artemanufrij** [comment]
that's a good point. I will test it on Juno
