### ISSUE TITLE
i don't know this???

### ISSUE THREAD

**Issue by torikulhabib** [artemanufrij/screencast#38]
Juno
![screenshot from 2018-07-27 15-31-42](https://user-images.githubusercontent.com/26135527/43310710-8e1fc36a-91b2-11e8-9328-c4d73f50355a.png)

**Comment by artemanufrij** [comment]
wow.... let me check it again...

**Comment by artemanufrij** [comment]
@torikulhabib could you test current master branch please?

**Comment by torikulhabib** [comment]
![screenshot from 2018-07-31 05-57-04](https://user-images.githubusercontent.com/26135527/43428077-a1209b3e-9486-11e8-9359-02b54b23048e.png)

 mr. @artemanufrij

**Comment by artemanufrij** [comment]
Thank you for your feedback...
